In [1]:
import numpy as np

7-1
Veiwing the two deminsional arrays as matrixes, the shape tuple of a two-deminsional array will display rows and columns as such: (#rows, #columns). The function only works on a homogenous arrays, meaning each array of n-demensions must contain the same number of elements. One could also say that the first nuber of the touple is the number of arrays in the touple, and the second number are the elements inside said arrays. For the array [[2,3,5] [5,7,11]], the shape touple would be (2,3)

In [2]:
'''7-2'''
#provided code
ppm = np.array([[ 20.80, 20.71, 21.72, 18.81],[ 19.91, 18.42, 20.73, 20.32],
                [ 17.32, 21.74, 23.19, 19.98]])

shape_of_ppm = np.shape(ppm) #code to obtain the shape, assigned to a variable
print(shape_of_ppm) #will print what it is equal to: (3,4)

(3, 4)


In [3]:
'''7-3'''
values = np.array([[2,3],[5,7],[11,13]])
print(values)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [35]:
'''7-4'''
#creates four-column floating point array called factors
factors = np.array([[0,1,2,3],[4,5,6,7]],dtype='d')
print(factors) #prints the factors array

[[0. 1. 2. 3.]
 [4. 5. 6. 7.]]


In [33]:
#creates three row five column array filled with sevens
seven = np.array([[7,7,7,7,7],[7,7,7,7,7],[7,7,7,7,7]],dtype='int')
print(seven) #prints the array

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
value = factors[1,2] #saves second row, third column of factors
first_row = factors[0] #saves first row of factors
subset = factors[0:,1:3] #subarray contains all (aka both) rows and the 2nd and 3rd columns of factors

#creates copy of factors so that code can be re-ran
factors_copy = factors
#first three elements of factors_copy equals last three elements in last row of factors_copy
factors_copy[0,:4] = factors_copy[1,:-3]

#tests
print(value)
print("")
print(first_row)
print("")
print(subset)
print("")
print(factors_copy)

6.0

[4. 4. 4. 4.]

[[4. 4.]
 [5. 6.]]

[[4. 4. 4. 4.]
 [4. 5. 6. 7.]]
