In [1]:
import numpy as np

7-1
Veiwing the two deminsional arrays as matrixes, the shape tuple of a two-deminsional array will display rows and columns as such: (#rows, #columns). The function only works on a homogenous arrays, meaning each array of n-demensions must contain the same number of elements. One could also say that the first nuber of the touple is the number of arrays in the touple, and the second number are the elements inside said arrays. For the array [[2,3,5] [5,7,11]], the shape touple would be (2,3)

In [2]:
'''7-2'''
#provided code
ppm = np.array([[ 20.80, 20.71, 21.72, 18.81],[ 19.91, 18.42, 20.73, 20.32],
                [ 17.32, 21.74, 23.19, 19.98]])

shape_of_ppm = np.shape(ppm) #code to obtain the shape, assigned to a variable
print(shape_of_ppm) #will print what it is equal to: (3,4)

(3, 4)


In [3]:
'''7-3'''
values = np.array([[2,3],[5,7],[11,13]])
print(values)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [4]:
'''7-4'''
#creates four-column floating point array called factors
factors = np.array([[0,1,2,3],[4,5,6,7]],dtype='d')
print(factors) #prints the factors array

[[0. 1. 2. 3.]
 [4. 5. 6. 7.]]


In [ ]:
'''7-5'''
#creates three row five column array filled with sevens
seven = np.array([[7,7,7,7,7],[7,7,7,7,7],[7,7,7,7,7]],dtype='int')
print(seven) #prints the array

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
'''7-6'''
value = factors[1,2] #saves second row, third column of factors
first_row = factors[0] #saves first row of factors
subset = factors[0:,1:3] #subarray contains all (aka both) rows and the 2nd and 3rd columns of factors

#first three elements of factors equals last three elements in last row of factors
factors[0,0:3] = factors[1,-3:]


#tests
print(value)
print("")
print(first_row)
print("")
print(subset)
print("")
print(factors)

6.0

[5. 6. 7. 3.]

[[6. 7.]
 [5. 6.]]

[[5. 6. 7. 3.]
 [4. 5. 6. 7.]]


In [ ]:
'''7-7'''
ppb = ppm*1000
print(ppb)

[[20800. 20710. 21720. 18810.]
 [19910. 18420. 20730. 20320.]
 [17320. 21740. 23190. 19980.]]


In [ ]:
'''7-8'''
#creates arbitrary datasets
data1 = np.array([[3,6],[4,8]])
data2 = np.array([[2,4],[9,18]])

#create new 2 deminsional array of same size
avg_between_both = np.zeros((2,2))

for i in range(2): #iterates by row
    for j in range(2): #iterates by column
        avg_between_both[i][j] = (data1[i][j]+data2[i][j])/2 #computes average

print(avg_between_both) #prints average

[[ 2.5  5. ]
 [ 6.5 13. ]]


In [ ]:
'''7-9'''

#creates and arbitrary data3 two deminsional array
data3 = np.array([[123,52451,67],[2,3333333333333333333,27]])

#uses numpy max function to assign max to max_data3
max_data3 = np.max(data3)

max2_data3 = 0 #creates a variable max2_data3 to be the second max... assigns 0 as placeholder

for k in range(2): #iterates through rows
    for n in range(3): #iterates through columns
        #checks element is greater than last, 2nd greatest
        if data3[k][n] > max2_data3 and data3[k][n] != max_data3: 
            max2_data3 = data3[k][n] #assigns second maximum

print(max_data3, ",", max2_data3)

        

3333333333333333333 , 52451
